Add videos module 3, 4 and 5
UBC-MDS/ds-toolbox pull request #99
Opened 2022-10-06 00:05 UTC by flor14

2022-10-07 23:40 UTC, joelostblom requested changes
@flor14 I went through module 3 and there seems to be several video not starting and stopping at the correct time. I made comments for these but I didn't go through the other two modules yet, could you double check that all three modules' videos start and stop at the correct point in the netflix preview and I poing me so I can  review again?

2022-10-07 23:40 UTC, joelostblom commented on chapters/en/module3.md
> +<slides source='module3/module3_03' shot='8' start='14:35' end='19:59'> </slides>
This video starts with you saying "Let's apply what we learned" from the following slide deck, maybe shift over 1-2 seconds?

This video also stops in the middle of a sentence

2022-10-07 23:40 UTC, joelostblom commented on chapters/en/module3.md
> +<slides source='module3/module3_05' shot='8' start='19:59' end='21:50'> </slides>
This seems to not be the entire video

2022-10-07 23:40 UTC, joelostblom commented on chapters/en/module3.md
> +<slides source='module3/module3_02' shot='8' start='3:46' end='14:35'> </slides>
This video stops before the "Lets apply what we learned" slide.

2022-10-07 23:40 UTC, joelostblom commented on chapters/en/module3.md
>  </exercise>
I think you missed one above `<exercise id='7' title='Committing changes to a local repository' type='slides, video'>` does not have the correct video added.

2022-10-07 23:40 UTC, joelostblom commented on chapters/en/module3.md
> +<slides source='module3/module3_06' shot='8' start='21:51' end='27:10'> </slides>
This starts in the middle of a slide.

2022-10-08 05:05 UTC, flor14 commented
Yes, I know. That is why I didn't assign you as reviewer. I will do this
tomorrow.

Thank you for your time and comments anyway 🙂

El vie., 7 de octubre de 2022 4:40 p. m., Joel Ostblom <
***@***.***> escribió:

> ***@***.**** requested changes on this pull request.
>
> @flor14 <https://github.com/flor14> I went through module 3 and there
> seems to be several video not starting and stopping at the correct time. I
> made comments for these but I didn't go through the other two modules yet,
> could you double check that all three modules' videos start and stop at the
> correct point in the netflix preview and I poing me so I can review again?
> ------------------------------
>
> In chapters/en/module3.md
> <https://github.com/UBC-MDS/ds-toolbox/pull/99#discussion_r990549174>:
>
> > @@ -134,7 +134,7 @@ When you are cloning a repository you are downloading a <code>.git</code> hidden
>  </exercise>
>
>  <exercise id='5' title="The staging area"  type='slides, video'>
> -<slides source='module3/module3_03' shot='8' start='3:42' end='4:35'> </slides>
> +<slides source='module3/module3_03' shot='8' start='14:35' end='19:59'> </slides>
>
> This video starts with you saying "Let's apply what we learned" from the
> following slide deck, maybe shift over 1-2 seconds?
>
> This video also stops in the middle of a sentence
> ------------------------------
>
> In chapters/en/module3.md
> <https://github.com/UBC-MDS/ds-toolbox/pull/99#discussion_r990549566>:
>
> > @@ -258,7 +258,7 @@ Have you include the README.md file in the staging area?
>  </exercise>
>
>  <exercise id='9' title='PUSHing changes from a remote repository'  type='slides, video'>
> -<slides source='module3/module3_05' shot='8' start='3:42' end='4:35'> </slides>
> +<slides source='module3/module3_05' shot='8' start='19:59' end='21:50'> </slides>
>
> This seems to not be the entire video
> ------------------------------
>
> In chapters/en/module3.md
> <https://github.com/UBC-MDS/ds-toolbox/pull/99#discussion_r990551095>:
>
> > @@ -88,7 +88,7 @@ When you clone a Git repository from GitHub you get the hidden `.git` directory
>  </exercise>
>
>  <exercise id='3' title="Version control repositories"  type='slides, video'>
> -<slides source='module3/module3_02' shot='8' start='3:42' end='4:35'> </slides>
> +<slides source='module3/module3_02' shot='8' start='3:46' end='14:35'> </slides>
>
> This video stops before the "Lets apply what we learned" slide.
> ------------------------------
>
> In chapters/en/module3.md
> <https://github.com/UBC-MDS/ds-toolbox/pull/99#discussion_r990551564>:
>
> > @@ -258,7 +258,7 @@ Have you include the README.md file in the staging area?
>  </exercise>
>
> I think you missed one above <exercise id='7' title='Committing changes
> to a local repository' type='slides, video'> does not have the correct
> video added.
> ------------------------------
>
> In chapters/en/module3.md
> <https://github.com/UBC-MDS/ds-toolbox/pull/99#discussion_r990552052>:
>
> > @@ -303,7 +303,7 @@ The HASH code it is automatically generated by Git each time you create a commit
>  </exercise>
>
>  <exercise id='11' title='PULLing changes from a remote repository'  type='slides, video'>
> -<slides source='module3/module3_06' shot='8' start='3:42' end='4:35'> </slides>
> +<slides source='module3/module3_06' shot='8' start='21:51' end='27:10'> </slides>
>
> This starts in the middle of a slide.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/UBC-MDS/ds-toolbox/pull/99#pullrequestreview-1135139166>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHB5G2QLQXM3UWZSZETYCCTWCCYIRANCNFSM6AAAAAAQ6A626I>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-08 15:58 UTC, joelostblom commented
Whooops sorry about that, I didn't understand this was still a draft

2022-10-08 17:35 UTC, flor14 commented
@joelostblom here is my research about the copyright of the images (#5). There is only one image that could be problematic, but let me know your thoughts.

These are the images I have checked for copyright. Remember that all of them are included in the videos. 

* Allison Horst image (module5_05 slides)
She suggests donating to [indigenous woman who hikes](https://github.com/allisonhorst/stats-illustrations#is-the-artwork-useful-for-your-teaching-materials-i-would-be-so-grateful-if-you-would). I think that it could be a nice gesture to donate something. Also, she wants alt text in the slide, I added it.

* PHD comics (module3_01 slides)
This is the most complicated because we should send an email
<img width="413" alt="image" src="https://user-images.githubusercontent.com/29610858/194719495-aed8dd7b-6843-4c4c-acbc-25279af36de3.png">

* XKCD comics (module3_04 slides)
https://xkcd.com/1296/
This work is licensed under a [Creative Commons Attribution-NonCommercial 2.5 License](https://creativecommons.org/licenses/by-nc/2.5/).

* The Turing Way (module3_01 slides)
I cited the image as it is mentioned [here](https://zenodo.org/record/3332808#.Y0GvQ1LMJwo). It is a CC-BY license.

2022-10-11 19:35 UTC, merged